site_name: My Personal Docs
site_url: https://chucnxwork.github.io/se-notebook/
site_author: Chuc NX

# Repository
repo_name: chucnxwork/se-notebook
repo_url: https://github.com/chucnxwork/se-notebook

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

# Page tree
nav:
  - Home: index.md
  - Software Engineering:
    - Apache/Xampp: SoftwareEngineering/ApacheXampp/ApacheXampp.md
    - Big Data: SoftwareEngineering/BigData/BigData.md
    - C:
      - Tim giao duong tron: SoftwareEngineering/C/timgiaoduongtron.cpp
      - Hinh tron, hinh chu nhat nho nhat: SoftwareEngineering/C/hinhtronhinhchunhatnhonhat.cpp
      - Hinh tron, hinh chu nhat nho nhat 2: SoftwareEngineering/C/hinhtronhinhchunhatnhonhat - Copy.cpp
    - CMD: SoftwareEngineering/CMD/batcmd.md
    - CMS (Content Management System): SoftwareEngineering/CMS/CMS.md
    - Crystal Reports: SoftwareEngineering/CrystalReports/CrystalReports.md
    - Hosting: SoftwareEngineering/Hosting/Hosting.md
    - HTML and Web: SoftwareEngineering/HTMLandWeb/HTML.md
    - Jasper Report: SoftwareEngineering/JasperReport.md
    - Java:
      - Java: SoftwareEngineering/Java/Java.md
      - AesEncryption.java: SoftwareEngineering/Java/AesEncryption.java
      - CustomHttpResponse.java: SoftwareEngineering/Java/CustomHttpResponse.java
      - HttpRequestUtils.java: SoftwareEngineering/Java/HttpRequestUtils.java
      - Utils.java: SoftwareEngineering/Java/Utils.java