site_name: My Docs
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tracking
    - toc.follow
    - toc.integrate

# Page tree
nav:
  - Home: index.md
  - Software Engineering:
    - Apache/Xampp: SoftwareEngineering/ApacheXampp/ApacheXampp.md